site_name: JURASSIC
site_url: https://slcs-jsc.github.io/jurassic/
repo_url: https://github.com/slcs-jsc/jurassic
docs_dir: manual
theme: material

nav:
    - Home: index.md
    - User manual:
        - Quickstart: quickstart.md
    - Further information:
        - References: references.md
        - Links: links.md
