site_name: MPTRAC
site_url: https://slcs-jsc.github.io/mptrac/
repo_url: https://github.com/slcs-jsc/mptrac
docs_dir: manual
theme: material

nav:
    - Home: index.md
    - User manual:
        - Quickstart: quickstart.md
    - Further information:
        - References: references.md
        - Links: links.md
