name: codecov

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: fetch
      uses: actions/checkout@v3
    - name: install
      run: sudo apt-get update ; sudo apt-get install gnuplot libgsl-dev lcov
    - name: make
      run: cd ./src ; STATIC=0 COV=1 make
    - name: check
      run: cd ./src ; STATIC=0 COV=1 make check
    - name: coverage
      run: cd ./src ; STATIC=0 COV=1 make coverage
    - name: upload
      uses: codecov/codecov-action@v3
      with:
        directory: ./src/
