name: codecov

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
    - name: fetch
      uses: actions/checkout@v5
    - name: install
      run: sudo apt-get update ; sudo apt-get install gnuplot libgsl-dev libnetcdf-dev libhdf5-dev lcov
    - name: make
      run: cd ./src ; make COV=1
    - name: make check
      run: cd ./src ; make check
    - name: make coverage
      run: cd ./src ; make coverage
    - name: upload
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        directory: ./src/
