name: coveralls

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - name: fetch
        uses: actions/checkout@v5

      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install -y gnuplot libgsl-dev libnetcdf-dev libhdf5-dev lcov

      - name: make coverage
        run: |
          cd ./src
          make coverage

      - name: upload
        uses: coverallsapp/github-action@v2
        with:
          file: ./src/coverage.info
          format: lcov
          fail-on-error: true
