name: testcase

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt-get update ; sudo apt-get install wget gnuplot
    - name: libs
      run: cd libs ; ./build.sh
    - name: make
      run: cd src ; make
    - name: example limb
      run: cd example/limb ; ./run.sh
    - name: example nadir
      run: cd example/nadir ; ./run.sh
